
ALTER TABLE "Category"        ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Product"         ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Modifier"        ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ProductModifier" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS "Order" (
  "id" SERIAL PRIMARY KEY,
  "tableCode" TEXT,
  "gross" INTEGER NOT NULL,
  "discount" INTEGER NOT NULL DEFAULT 0,
  "net" INTEGER NOT NULL,
  "cost" INTEGER NOT NULL,
  "printed" BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS "OrderItem" (
  "id" SERIAL PRIMARY KEY,
  "orderId" INTEGER NOT NULL REFERENCES "Order"("id") ON DELETE CASCADE,
  "productId" INTEGER,
  "productName" TEXT NOT NULL,
  "quantity" INTEGER NOT NULL DEFAULT 1,
  "unitPrice" INTEGER NOT NULL,
  "unitCost" INTEGER NOT NULL,
  "subtotal" INTEGER NOT NULL,
  "subtotalCost" INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "OrderItemModifier" (
  "id" SERIAL PRIMARY KEY,
  "orderItemId" INTEGER NOT NULL REFERENCES "OrderItem"("id") ON DELETE CASCADE,
  "modifierId" INTEGER,
  "modifierName" TEXT NOT NULL,
  "quantity" INTEGER NOT NULL DEFAULT 1,
  "priceDelta" INTEGER NOT NULL,
  "costDelta" INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "DailyPromo" (
  "id" SERIAL PRIMARY KEY,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "price" INTEGER NOT NULL,
  "cost" INTEGER NOT NULL DEFAULT 0,
  "imageUrl" TEXT,
  "active" BOOLEAN NOT NULL DEFAULT FALSE,
  "startDate" TIMESTAMP,
  "endDate" TIMESTAMP,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);
